server.port=8080
spring.application.name=rent-a-car-backend-my
spring.datasource.url=jdbc:postgresql://localhost:5432/rentacar
spring.datasource.username=kubraeser
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

jwt.secret=rentacar-secret-key-change-in-production
jwt.expiration-ms=36000000